name: "CI"

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: volta-cli/action@v1

    - name: install
      run: yarn
  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: lint
      run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: test
      run: yarn test

