name: "CI"

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Setup node
      uses: volta-cli/action@v1
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install
      run: yarn
    - name: lint
      run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup node
      uses: volta-cli/action@v1
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: install
      run: yarn

    #- name: test
    #  run: yarn test

    - name: test
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: yarn coverage
        coverageLocations: |
          ${{github.workspace}}/packages/buttons/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/cards/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/foundation/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/inputs/coverage/lcov.info:lcov
          ${{github.workspace}}/packages/layouts/coverage/lcov.info:lcov
