name: "CI"

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [ubuntu-20.04, macos-11.0]

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: volta-cli/action@v1

    - name: install
      run: yarn
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
        

