name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node with volta
      uses: volta-cli/action@v1
      with:
        node-version: 12.x

    - name: install
      run: yarn
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
        

